/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package user.entelgy.data.service.model.impl;

import user.entelgy.data.service.model.UserEntelgy;
import user.entelgy.data.service.service.UserEntelgyLocalServiceUtil;

/**
 * The extended model base implementation for the UserEntelgy service. Represents a row in the &quot;ENTELGYUSER_UserEntelgy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserEntelgyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserEntelgyImpl
 * @see UserEntelgy
 * @generated
 */
public abstract class UserEntelgyBaseImpl
	extends UserEntelgyModelImpl implements UserEntelgy {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user entelgy model instance should use the <code>UserEntelgy</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserEntelgyLocalServiceUtil.addUserEntelgy(this);
		}
		else {
			UserEntelgyLocalServiceUtil.updateUserEntelgy(this);
		}
	}

}