/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package user.entelgy.data.service.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import user.entelgy.data.service.model.UserEntelgy;
import user.entelgy.data.service.service.UserEntelgyLocalService;
import user.entelgy.data.service.service.UserEntelgyLocalServiceUtil;
import user.entelgy.data.service.service.persistence.UserEntelgyPersistence;

/**
 * Provides the base implementation for the user entelgy local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link user.entelgy.data.service.service.impl.UserEntelgyLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see user.entelgy.data.service.service.impl.UserEntelgyLocalServiceImpl
 * @generated
 */
public abstract class UserEntelgyLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, UserEntelgyLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UserEntelgyLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>UserEntelgyLocalServiceUtil</code>.
	 */

	/**
	 * Adds the user entelgy to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UserEntelgyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param userEntelgy the user entelgy
	 * @return the user entelgy that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UserEntelgy addUserEntelgy(UserEntelgy userEntelgy) {
		userEntelgy.setNew(true);

		return userEntelgyPersistence.update(userEntelgy);
	}

	/**
	 * Creates a new user entelgy with the primary key. Does not add the user entelgy to the database.
	 *
	 * @param userEntelgyId the primary key for the new user entelgy
	 * @return the new user entelgy
	 */
	@Override
	@Transactional(enabled = false)
	public UserEntelgy createUserEntelgy(long userEntelgyId) {
		return userEntelgyPersistence.create(userEntelgyId);
	}

	/**
	 * Deletes the user entelgy with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UserEntelgyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param userEntelgyId the primary key of the user entelgy
	 * @return the user entelgy that was removed
	 * @throws PortalException if a user entelgy with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UserEntelgy deleteUserEntelgy(long userEntelgyId)
		throws PortalException {

		return userEntelgyPersistence.remove(userEntelgyId);
	}

	/**
	 * Deletes the user entelgy from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UserEntelgyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param userEntelgy the user entelgy
	 * @return the user entelgy that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UserEntelgy deleteUserEntelgy(UserEntelgy userEntelgy) {
		return userEntelgyPersistence.remove(userEntelgy);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return userEntelgyPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UserEntelgy.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return userEntelgyPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>user.entelgy.data.service.model.impl.UserEntelgyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return userEntelgyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>user.entelgy.data.service.model.impl.UserEntelgyModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return userEntelgyPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return userEntelgyPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return userEntelgyPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public UserEntelgy fetchUserEntelgy(long userEntelgyId) {
		return userEntelgyPersistence.fetchByPrimaryKey(userEntelgyId);
	}

	/**
	 * Returns the user entelgy with the primary key.
	 *
	 * @param userEntelgyId the primary key of the user entelgy
	 * @return the user entelgy
	 * @throws PortalException if a user entelgy with the primary key could not be found
	 */
	@Override
	public UserEntelgy getUserEntelgy(long userEntelgyId)
		throws PortalException {

		return userEntelgyPersistence.findByPrimaryKey(userEntelgyId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(userEntelgyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UserEntelgy.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("userEntelgyId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			userEntelgyLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(UserEntelgy.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"userEntelgyId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(userEntelgyLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UserEntelgy.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("userEntelgyId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return userEntelgyPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement UserEntelgyLocalServiceImpl#deleteUserEntelgy(UserEntelgy) to avoid orphaned data");
		}

		return userEntelgyLocalService.deleteUserEntelgy(
			(UserEntelgy)persistedModel);
	}

	@Override
	public BasePersistence<UserEntelgy> getBasePersistence() {
		return userEntelgyPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return userEntelgyPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the user entelgies.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>user.entelgy.data.service.model.impl.UserEntelgyModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of user entelgies
	 * @param end the upper bound of the range of user entelgies (not inclusive)
	 * @return the range of user entelgies
	 */
	@Override
	public List<UserEntelgy> getUserEntelgies(int start, int end) {
		return userEntelgyPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of user entelgies.
	 *
	 * @return the number of user entelgies
	 */
	@Override
	public int getUserEntelgiesCount() {
		return userEntelgyPersistence.countAll();
	}

	/**
	 * Updates the user entelgy in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UserEntelgyLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param userEntelgy the user entelgy
	 * @return the user entelgy that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UserEntelgy updateUserEntelgy(UserEntelgy userEntelgy) {
		return userEntelgyPersistence.update(userEntelgy);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			UserEntelgyLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		userEntelgyLocalService = (UserEntelgyLocalService)aopProxy;

		_setLocalServiceUtilService(userEntelgyLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UserEntelgyLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UserEntelgy.class;
	}

	protected String getModelClassName() {
		return UserEntelgy.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = userEntelgyPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		UserEntelgyLocalService userEntelgyLocalService) {

		try {
			Field field = UserEntelgyLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, userEntelgyLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected UserEntelgyLocalService userEntelgyLocalService;

	@Reference
	protected UserEntelgyPersistence userEntelgyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		UserEntelgyLocalServiceBaseImpl.class);

}